1.1
LING VPN 
Update File 21-11-22 
รายการเซิฟเวอร์ 
AUS 5 SERVER 
CA 10 SERVER 
SG-DIGTAL 10 SERVER 
SG-SECURE 10 SERVER 
TH-IDC 10 SERVER 
TH-READY 10 SERVER 
VIP-CAT 4 SERVER เช่า 
VIP-DBEST 1 SERVER 
VIP-DCSL 1 SERVER 
VIP-READY 1 SERVER 
VIP-SG 3 SERVER
BY เสี่ยเอก มงคล
